name: "build"
on:
   workflow_dispatch:
            
jobs:
    build:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 23
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'jetbrains'
                    java-version: 23
                    architecture: x64
                    cache: 'maven'
            -   name: Build with Maven
                run: mvnw clean install && mvn --no-transfer-progress verify
