name: "build"
on:
   workflow_dispatch:
            
jobs:
    build:
        runs-on: self-hosted
        strategy:
            fail-fast: true
            matrix:
                os: [ windows-latest]
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 17
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
